name: Build Snap

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/action-build@v1
        id: snapcraft
      - uses: actions/upload-artifact@v4
        with:
          name: folio-pdf-reader-snap
          path: ${{ steps.snapcraft.outputs.snap }}
